language: node_js
node_js:
  - 14
script:
- yarn generate
- printf 'nina.metodieva.pro' > dist/CNAME
- cp 'README.md' dist
before_install:
  - openssl aes-256-cbc -K $encrypted_394136aef2ef_key -iv $encrypted_394136aef2ef_iv -in .env.enc -out .env -d
branches:
  only:
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    on:
      tags: true
  - provider: pages
    skip_cleanup: true
    local_dir: dist
    target_branch: master
    github_token: $GITHUB_TOKEN
    on:
      tags: true
